print("hello pepzi")
print("hello pepzi")
print("hello pepzi")
print("hello pepzi")
print("hello pepzi")
print("hello pepzi")
print("hello pepzi")
print("hello pepzi")
vim.keymap.set("n", "asdf", ":echo 'hello'")
